[package]
name = "sayoasm"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "sayoasm"
path = "src/main.rs"

[dependencies]
sayo_assembler = { path = "../sayo_assembler" }
sayo_parser = { path = "../sayo_parser" }
clap = { version = "4.0", features = ["derive"] }
anyhow = "1.0"
